In [1]:
# matrix multiplication.

import numpy as np

a = np.array([[4, 2, 3], [4, 0, 2]])
b = np.array([[2, 2], [9, 5],[1,0]])
def mult(a,b):
    first=a.shape
    second=b.shape
    
    if len(first)==len(second) and first[1] == second[0]: # check the possibilty
        return np.dot(a, b) #dot product of the matrices
    else:
        print("Error! Please enter the correct dimensions of the matrix")
print(mult(a,b))

[[29 18]
 [10  8]]


In [2]:
#counting vowels and consonants in a string.
input_string="Good Morning!"
def count(input_string):
    # Convertion of input string to lowercase
    input_string=input_string.lower()
   # initialising count for vowels and consonants 
    vowels=0
    consonants=0
    for i in range(len(input_string)):
        # Check if the character is a letter
        if input_string[i].isalpha():
            # Check if the character is a vowel
            if input_string[i] in ['a','i','e','o','u']:
                vowels+=1
            else:
                consonants+=1
    return (vowels,consonants)
value=count(input_string)
print("The no of vowels are : ",value[0])
print("The no of consonants are : ",value[1])

The no of vowels are :  4
The no of consonants are :  7


In [3]:
# intersection of two lists

list_1=[1,3,4,5,6,7]
list_2=[2,4,5,6,7,8,0]

def intersection(list_1,list_2):
    final_list=[] #empty list
    for element in list_1:
        if element in list_2: # check if the element is present in list2
            final_list.append(element)
    return final_list

print(intersection(list_1,list_2))


[4, 5, 6, 7]


In [4]:
# creating transpose
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

def trans(a):
    transpose = [] # empty list
    sha = a.shape
    first = sha[0]
    sec = sha[1]
    for i in range(sec):  # Loop over columns instead of rows
        row = []  # Create a new row for the transpose
        for j in range(first):
            row.append(a[j][i])
        transpose.append(row)
    return np.array(transpose)

print("Original Matrix")
print(a)
print("Transpose")
print(trans(a))


Original Matrix
[[1 2 3]
 [4 5 6]]
Transpose
[[1 4]
 [2 5]
 [3 6]]
